/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects and checked in here so
// TypeScript has the expected ambient types before the first local build.
